(function(g){var window=this;'use strict';var Mgb=function(a,b){if(!Number.isFinite(a))return String(a);a=String(a);var c=a.indexOf(".");-1===c&&(c=a.length);var d="-"===a[0]?"-":"";d&&(a=a.substring(1));return d+(0,g.F8a)("0",Math.max(0,b-c))+a},Ngb=function(){return{G:"svg",
X:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},W:[{G:"path",X:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},Ogb=function(){return{G:"svg",
X:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},W:[{G:"path",X:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},Qgb=function(a){"number"===typeof a?(this.date=Pgb(a,0,1),p6(this,1)):g.Pa(a)?(this.date=Pgb(a.getFullYear(),a.getMonth(),a.getDate()),p6(this,a.getDate())):(this.date=new Date(g.Va()),a=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),p6(this,a))},Pgb=function(a,b,c){b=new Date(a,b,c);
0<=a&&100>a&&b.setFullYear(b.getFullYear()-1900);return b},p6=function(a,b){a.getDate()!=b&&a.date.setUTCHours(a.date.getUTCHours()+(a.getDate()<b?1:-1))},q6=function(a,b){g.yS.call(this,a,{G:"div",
N:"ytp-reminder-menu",X:{role:"menu",tabindex:"-1"},W:[{G:"div",N:"ytp-reminder-menu-contents",W:[{G:"div",N:"ytp-reminder-menu-items"}]}]},100,!0);this.buttonElement=b;this.j=[];this.menuPopupRenderer=void 0;this.items=this.Da("ytp-reminder-menu-items");this.hide()},Sgb=function(a){var b=Rgb(a),c=0,d={};
for(c=0;c<b.length;d={xI:d.xI},c++){var e=a.j[c];e||(e=new g.V({G:"div",N:"ytp-reminder-menu-item",X:{role:"menuitem",tabindex:"0"},W:[{G:"div",N:"ytp-reminder-menu-item-icon",ra:"{{icon}}"},{G:"div",N:"ytp-reminder-menu-item-label",ra:"{{text}}"}]}),d.xI=c,e.Ra("click",function(l){return function(){var m=l.xI;a.Hb();m=Rgb(a)[m];a.ma("reminderMenuItemClicked",m.serviceEndpoint||m.command)}}(d)),e.Ga(a.items),a.j[c]=e);
var f=b[c],h=null;switch(f.icon&&f.icon.iconType){case "NOTIFICATIONS":h=Ngb();break;case "NOTIFICATIONS_NONE":h=Ogb();break;case "NOTIFICATIONS_ACTIVE":h=g.rDa()}f=f.text?g.qE(f.text):"";e.update({icon:h,text:f})}for(;c<a.j.length;)a.j.pop().dispose();0===c?a.Hb():a.md(a.buttonElement)},Rgb=function(a){return(a.menuPopupRenderer&&a.menuPopupRenderer.items||[]).reduce(function(b,c){c&&c.menuServiceItemRenderer&&b.push(c.menuServiceItemRenderer);
return b},[])},r6=function(a){g.V.call(this,{G:"div",
W:[{G:"button",Ia:["ytp-offline-slate-button","ytp-button"],W:[{G:"div",N:"ytp-offline-slate-button-icon",ra:"{{icon}}"},{G:"div",N:"ytp-offline-slate-button-text",ra:"{{text}}"}]}]});this.F=a;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.u=void 0;this.C=this.j=null;(this.buttonElement=this.Da("ytp-offline-slate-button"))&&this.S(this.buttonElement,"click",this.D);this.hide()},Ugb=function(a,b,c){!a.toggleButtonRenderer&&b&&b.toggleButtonRenderer?a.toggleButtonRenderer=
b.toggleButtonRenderer:b&&b.toggleButtonRenderer||(a.toggleButtonRenderer=null);
!a.upcomingEventReminderButtonRenderer&&c&&g.S(c,Tgb)?a.upcomingEventReminderButtonRenderer=g.S(c,Tgb):c&&g.S(c,Tgb)||(a.upcomingEventReminderButtonRenderer=null);s6(a)},s6=function(a){if(a.toggleButtonRenderer){var b=a.toggleButtonRenderer;
if(b.isToggled){var c=b.toggledText?g.qE(b.toggledText):"";a.update({text:c,icon:Vgb(b.toggledIcon)})}else c=b.defaultText?g.qE(b.defaultText):"",a.update({text:c,icon:Vgb(b.defaultIcon)});a.show()}else a.upcomingEventReminderButtonRenderer?(b=Wgb(a))?(c=b.text?g.qE(b.text):"",a.update({text:c,icon:Vgb(b.icon)}),a.show()):a.hide():a.hide()},Ygb=function(a,b,c){a.C||(a.C=new g.qC(a.F.V().Uk));
var d={context:g.zB(a.C.config_||g.yB())};g.OE()&&(d.context.clientScreenNonce=g.OE());d.params=c;g.rC(a.C,b,d,{timeout:5E3,onSuccess:function(){a.upcomingEventReminderButtonRenderer&&a.u&&(a.upcomingEventReminderButtonRenderer.currentState=a.u,a.u=void 0)},
onError:function(){Xgb(a)},
onTimeout:function(){Xgb(a)}})},Xgb=function(a){a.toggleButtonRenderer?(a.toggleButtonRenderer.isToggled=!a.toggleButtonRenderer.isToggled,s6(a)):a.upcomingEventReminderButtonRenderer&&(a.u=void 0,s6(a))},Vgb=function(a){if(!a)return null;
switch(a.iconType){case "NOTIFICATIONS":return Ngb();case "NOTIFICATIONS_NONE":return Ogb();case "NOTIFICATIONS_ACTIVE":return g.rDa();default:return null}},Wgb=function(a){if(!a.upcomingEventReminderButtonRenderer)return null;
var b=a.u||a.upcomingEventReminderButtonRenderer.currentState;a=g.w(a.upcomingEventReminderButtonRenderer.states||[]);for(var c=a.next();!c.done;c=a.next())if((c=g.S(c.value,Zgb))&&c.state===b&&c.button&&g.S(c.button,g.DM))return g.S(c.button,g.DM);return null},$gb=function(a){g.V.call(this,{G:"div",
N:"ytp-offline-slate",W:[{G:"div",N:"ytp-offline-slate-background"},{G:"div",N:"ytp-offline-slate-bar",W:[{G:"span",N:"ytp-offline-slate-icon",W:[{G:"svg",X:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},W:[{G:"path",X:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{G:"circle",X:{cx:"12",cy:"12",r:"3"}}]}]},{G:"span",N:"ytp-offline-slate-messages",W:[{G:"div",N:"ytp-offline-slate-main-text",X:{"aria-label":"{{label}}"},ra:"{{mainText}}"},{G:"div",N:"ytp-offline-slate-subtitle-text",ra:"{{subtitleText}}"}]},{G:"span",N:"ytp-offline-slate-buttons"}]},{G:"button",Ia:["ytp-offline-slate-close-button","ytp-button"],W:[g.DQ()]},{G:"button",Ia:["ytp-offline-slate-open-button","ytp-button"],W:[g.CQ()]}]});var b=this;this.api=a;this.j=this.u=null;this.background=this.Da("ytp-offline-slate-background");
this.B=this.Da("ytp-offline-slate-bar");this.D=new g.Ip(function(){g.Qp(b.B,"ytp-offline-slate-bar-fade")},15E3);
this.I=!1;this.C=new g.Ip(function(){g.Qp(b.element,"ytp-offline-slate-collapsed")},15E3);
g.J(this,this.C);g.J(this,this.D);this.countdownTimer=new g.Ip(this.FY,1E3,this);this.S(a,"presentingplayerstatechange",this.JY);this.S(a,"livestatedata",this.Qa);a=this.Da("ytp-offline-slate-close-button");this.S(a,"click",function(){g.Qp(b.element,"ytp-offline-slate-collapsed")});
a=this.Da("ytp-offline-slate-open-button");this.S(a,"click",function(){g.Sp(b.element,"ytp-offline-slate-collapsed")});
this.hide();a=this.getVideoData();a.getPlayerResponse()&&(a=a.getPlayerResponse().playabilityStatus)&&this.Qa(a);a=8===this.api.getPresentingPlayerType()&&!this.getVideoData().vl;var c=8===this.api.getPresentingPlayerType();g.Up(this.element,"ytp-offline-slate-premiere-trailer",a);g.Up(this.element,"ytp-offline-slate-hide-background",c)},ahb=function(a,b,c){if(b){var d=null!=b.subtitleText?g.qE(b.subtitleText):"";
c=c?c:null!=b.mainText?g.qE(b.mainText):"";var e,f,h,l;b=null!=(l=null==(e=b.mainText)?void 0:null==(f=e.accessibility)?void 0:null==(h=f.accessibilityData)?void 0:h.label)?l:c;a.update({mainText:c,subtitleText:d,label:b});g.Up(a.element,"ytp-offline-slate-single-text-line",!d);g.Up(a.B,"ytp-offline-slate-bar-hidden",!c&&!d)}},t6=function(a,b){var c=(0,g.QA)();
this.module="heartbeat";this.trigger=a;this.j=b;this.B=c},ihb=function(a){g.sT.call(this,a);
var b=this;this.J=!1;this.T=0;this.D=!1;this.u=new g.Ip(function(){var e=b.player.V(),f=b.getVideoData();u6(b)&&(bhb(b)?chb(b,e,f):(dhb(b),ehb(b,e,f)))},0);
this.j=this.heartbeatParams=null;this.C=!1;this.I=new g.Ii(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.Z=new g.qC(void 0);this.ea=this.attestationResponse=void 0;this.utcOffsetMinutes=-(new Qgb).getTimezoneOffset();this.B=new g.aI(this);g.J(this,this.u);g.J(this,this.B);dhb(this);fhb(this);this.B.S(a,"heartbeatparams",this.YC);this.B.S(a,"presentingplayerstatechange",this.d_);this.B.S(a,"videoplayerreset",this.e_);this.B.S(a,g.iE("heartbeat"),this.onCueRangeEnter);this.C&&this.j&&
ghb(this,this.j);var c=new g.gE(1E3,0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),d=new g.gE(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});a.Ge([c,d]);hhb(this)},hhb=function(a){var b=a.getVideoData();
b.jm&&(b=b.botguardData)&&g.LIa(b,a.player.V())},dhb=function(a){var b=a.getVideoData();
if(b.jm&&(b=new g.HIa(b),g.SR.isInitialized()||3<=a.sequenceNumber)){var c=null;if(b.videoData.qk){var d=g.IIa(b);if(d){c={};var e={};d=d.split("&");d=g.w(d);for(var f=d.next();!f.done;f=d.next())f=f.value.split("="),2===f.length&&(e[f[0]]=f[1]);e.r1a&&(c.webResponse=e.r1a);e.r1c&&(c.error=jhb[Number(e.r1c)]);c.challenge=b.videoData.qk}}a.attestationResponse=c||void 0}},bhb=function(a){var b=a.getVideoData();
if(!g.QM(a.getVideoData())||b.ES)return!1;if(b.useInnertubeDrmService()&&b.I){a="playready"===b.I.flavor&&b.K("html5_innertube_heartbeats_for_playready");var c="widevine"===b.I.flavor&&b.K("html5_innertube_heartbeats_for_widevine");b=g.uJ(b.I)&&b.K("html5_innertube_heartbeats_for_fairplay");return!(a||c||b)}return!0},khb=function(a){if(bhb(a))return!!a.heartbeatParams;
var b=a.getVideoData();return g.QM(a.getVideoData())&&b.useInnertubeDrmService()&&!b.Vk&&!b.UI?!1:!!b.heartbeatToken},v6=function(a,b){if(!a.u.isActive()&&a.J){var c=a.getVideoData();
if(khb(a)||c.isLivePlayback){if(void 0===b)if(a.D)if(a.C)b=7500;else{var d;b=(null==(d=a.heartbeatParams)?0:d.interval)?1E3*a.heartbeatParams.interval:a.getVideoData().lS||6E4}else b=1E3;a.u.start(b)}}},ohb=function(a,b,c){b.Am&&(c=g.Xi(c,{internalipoverride:b.Am}));
var d={cpn:b.clientPlaybackNonce};b.contextParams&&(d.context_params=b.contextParams);b.Ib&&(d.kpt=b.Ib);c=g.Xi(c,d);g.My(c,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(e){if(!a.u.isActive()&&u6(a)){a.I.reset();a.sequenceNumber++;e=e.responseText;var f=lhb(e);if(f){a.player.Na("onHeartbeat",f);var h="ok"===f.status?f.stop_heartbeat?2:0:"stop"===f.status?1:"live_stream_offline"===f.status?0:-1}else h=(h=e.match(mhb))?"0"===h[1]?0:1:-1;nhb(a,f,e,h)}},
onError:function(e){u6(a)&&w6(a,!0,"net-"+e.status)},
onTimeout:function(){u6(a)&&w6(a,!0,"timeout")},
withCredentials:!0})},chb=function(a,b,c){var d;
if(null!=(d=a.heartbeatParams)&&d.url){var e=g.Xi(a.heartbeatParams.url,{request_id:g.era()});c.oa&&(e=g.Xi(e,{vvt:c.oa}),c.mdxEnvironment&&(e=g.Xi(e,{mdx_environment:c.mdxEnvironment})));g.cL(b,c.oauthToken).then(function(f){f&&(e=g.Xi(e,{access_token:f}));ohb(a,c,e)})}},u6=function(a){var b=a.getVideoData();
return 3===a.player.getPresentingPlayerType()||g.hO(a.player.Eb(a.getPlayerType()),4)?!1:khb(a)||b.isLivePlayback?!0:(x6(a),!1)},ehb=function(a,b,c){var d,e={videoId:c.videoId,
sequenceNumber:a.sequenceNumber,heartbeatServerData:null!=(d=a.oa)?d:c.heartbeatServerData};a.ea=a.attestationResponse;c.jm&&(e.attestationResponse=a.ea);var f=g.WR(c),h;d=null!=(h=f.client)?h:{};d.utcOffsetMinutes=a.utcOffsetMinutes;e.context=f;e.cpn=c.clientPlaybackNonce;if(h="undefined"!==typeof Intl?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)d.timeZone=h;h={heartbeatChecks:[]};if(d=c.getPlayerResponse())c.heartbeatToken&&(e.heartbeatToken=c.heartbeatToken),(d=d.playabilityStatus)&&
(d=d.liveStreamability)&&d.liveStreamabilityRenderer&&h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");c.heartbeatToken&&h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");if(g.VK(b)){h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED");f=phb(a);d={};null!==f&&(d.clientPlayerPositionUtcMillis=f);var l,m;f=(null==(m=null==(l=a.player.wb())?void 0:g.HT(l))?void 0:m.freePreviewWatchedDuration)||0;0<f&&(d.freePreviewWatchedDuration={seconds:""+f});h.unpluggedParams=d}e.heartbeatRequestParams=
h;c.isLivePlayback?(l=phb(a),null!==l&&(e.playbackState||(e.playbackState={}),e.playbackState.playbackPosition={utcTimeMillis:l})):b.K("enable_heartbeat_vod_playback_position")&&(l=qhb(a),null!==l&&(e.playbackState||(e.playbackState={}),e.playbackState.playbackPosition={streamTimeMillis:l}));a.player.ma("heartbeatRequest",e);var n={timeout:3E4,onSuccess:function(p){if(!a.u.isActive()&&u6(a)){var q=a.getVideoData(),t=q.jm&&null==a.ea,v;q.jm=!(null==(v=p.heartbeatAttestationConfig)||!v.requiresAttestation)||
t;t=p.playabilityStatus;v=JSON.stringify(t)||"{}";p.authenticationMismatch&&a.player.xa("authshear",{});var z=-1;var B=p.playabilityStatus;B&&(a.player.Na("onHeartbeat",B),"OK"===B.status?z=p.stopHeartbeat?2:0:"UNPLAYABLE"===B.status?z=1:"LIVE_STREAM_OFFLINE"===B.status&&(z=0));a.sequenceNumber&&-1===z||a.I.reset();a.sequenceNumber++;p.heartbeatServerData&&(a.oa=p.heartbeatServerData);q.WI=p;p.playerCueRanges&&0<p.playerCueRanges.length&&(q.cueRanges=p.playerCueRanges,q.ma("dataupdated"));var G,O;
(null==(G=p.progressBarConfig)?0:G.progressBarStartPosition)&&(null==(O=p.progressBarConfig)?0:O.progressBarEndPosition)&&(q.progressBarStartPosition=p.progressBarConfig.progressBarStartPosition,q.progressBarEndPosition=p.progressBarConfig.progressBarEndPosition);nhb(a,t,v,z)}},
onError:function(p){u6(a)&&w6(a,!0,"net-"+p.status)},
onTimeout:function(){u6(a)&&w6(a,!0,"timeout")}};
g.cL(b,g.kN(c)).then(function(p){p&&(n.zS="Bearer "+p);g.rC(a.Z,"player/heartbeat",e,n)})},nhb=function(a,b,c,d){-1===d?(b="decode "+g.$f(c,3),w6(a,!1,b)):2===d?(x6(a),a.D=!0):(a.T=0,a.u.stop(),1===d?(a.D=!1,a.player.Og("heartbeat.stop",2,a.Bf(c)),g.xA("heartbeatActionPlayerHalted",rhb(b))):(a.D=!0,c=0,a.C&&b&&(c=ghb(a,b),a.player.ma("livestatedata",b)),c?v6(a,c):v6(a)))},ghb=function(a,b){var c=b.liveStreamability&&b.liveStreamability.liveStreamabilityRenderer,d=!(!c||!(c.switchStreamsImmediately||
c.transitionTiming&&"STREAM_TRANSITION_TIMING_IMMEDIATELY"===c.transitionTiming)),e=shb(c),f=a.getVideoData(),h=a.player.Eb(a.getPlayerType()),l=h.fd()&&!g.WM(f)&&!a.player.isAtLiveHead(a.getPlayerType());
if(f.V().je()){var m,n=(null==(m=a.player.Ce())?void 0:m.jc())||{};n.status=b.status||"";n.dvr=""+ +l;n["switch"]=""+ +d;n.ended=""+ +!(!c||!c.displayEndscreen);a.player.xa("heartbeat",n)}if(l&&!d)return e;d=c&&c.streamTransitionEndpoint&&g.S(c.streamTransitionEndpoint,g.FM);if("STREAM_TRANSITION_TIMING_AT_STREAM_END"===(c&&c.transitionTiming))a.getVideoData().transitionEndpointAtEndOfStream=d;else{if(l=d)(l=d&&d.videoId)?(a.player.Kn(l,{autonav:"1"},void 0,!0,!0,d,g.kN(a.getVideoData())),a.zG("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE",
"HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",b),l=!0):l=!1;if(l)return e}if("OK"===b.status.toUpperCase()){d=c&&c.broadcastId;l=a.j&&a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer&&a.j.liveStreamability.liveStreamabilityRenderer.broadcastId;m=d!==l&&null!=d;if(!f.hlsvp&&!f.ib||m){var p={video_id:f.videoId};f.LJ&&(p.is_live_destination="1");a.player.K("web_player_heartbeat_request_watch_next")||(p.disable_watch_next=!0,p.raw_watch_next_response=f.jd);
p.autonav_state=f.autonavState;p.oauth_token=f.oauthToken;p.force_gvi=f.zm;p.Sl=f.Sl;f.J&&(p.vss_credentials_token=f.J,p.vss_credentials_token_type=f.ek);f.oa&&(p.vvt=f.oa);c=void 0;f.hlsvp||f.ib?m&&(c=new t6("broadcastIdChanged",l+","+d),a.zG("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",b)):(d&&(c=new t6("formatsReceived",""+d)),a.zG("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",b));a.player.loadVideoByPlayerVars(p,
void 0,void 0,void 0,c);return e}a.player.og("heartbeat",a.getPlayerType())}c&&c.displayEndscreen&&(a.offlineSlate?(a=a.offlineSlate,a.I=!0,a.zb&&a.api.Sz()):g.jP(h)&&(f=(null==(p=a.player.Ce())?void 0:p.jc())||{},a.player.xa("hbse",f,!0),a.player.Sz(),a.player.Na("onLiveMediaEnded",b)));return e},shb=function(a){var b=0;
a&&a.pollDelayMs&&(a=Number(a.pollDelayMs))&&(b=a);return b},w6=function(a,b,c){var d=a.player.V();
if(!a.u.isActive()){a.u.stop();a.T++;var e=b?"heartbeat.net":"heartbeat.servererror";var f=a.getVideoData();if(f.nS||b&&!g.QM(a.getVideoData())&&!khb(a)&&f.isLivePlayback)f=!1;else{var h,l;(null==(l=a.heartbeatParams)?0:l.Jz)?h=a.heartbeatParams.Jz:h=f.mS||5;f=a.T>=h}f?(g.xA("heartbeatActionPlayerHalted",b?{enforcedPolicyToHaltOnNetworkFailure:!0}:rhb()),(b=a.getVideoData())&&b.isLivePlayback?a.player.Og(e,1,"Video playback interrupted. Please try again.",c):a.player.Og(e,1,"Sorry, there was an error licensing this video.",
c)):(d.K("html5_report_non_fatal_heartbeat_error")&&a.player.Uq(e,{msg:c}),v6(a,a.I.getValue()),g.Ji(a.I))}},rhb=function(a){var b={enforcedPolicyToHaltOnNetworkFailure:!1};
a&&(b.serializedServerContext=a.additionalLoggingData);return b},x6=function(a){a.T=0;
a.u.stop();a.D=!1;a.sequenceNumber=0},fhb=function(a){var b=a.getVideoData(),c=a.player.V();
if(b.isLivePlayback)if(g.LJ(c.D)){a.C=!0;a.J=!0;if(!g.JK(c)||g.VK(c))a.offlineSlate=new $gb(a.player),g.J(a,a.offlineSlate),g.uS(a.player,a.offlineSlate.element,4);(b=b.getPlayerResponse())&&b.playabilityStatus&&(a.j=b.playabilityStatus);var d;"UNPLAYABLE"!==(null==(d=a.j)?void 0:d.status)&&(a.j?(d=shb(a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer))?v6(a,d):v6(a,7500):v6(a,1E3))}else a.player.Og("html5.unsupportedlive",2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");else g.wb(b.Fa,
"heartbeat")&&a.player.og("heartbeat",a.getPlayerType())},phb=function(a){return(a=a.player.getProgressState(a.getPlayerType()).ingestionTime)&&isFinite(a)?""+Math.floor(1E3*a):null},qhb=function(a){return(a=a.player.getCurrentTime(a.getPlayerType()))&&isFinite(a)?""+Math.floor(1E3*a):null},lhb=function(a){try{var b=JSON.parse(a);
return null!=b?b:void 0}catch(c){}},jhb=["ATTESTATION_ERROR_UNKNOWN",
"ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"],thb={Opa:["BC","AD"],Npa:["Before Christ","Anno Domini"],kKa:"JFMAMJJASOND".split(""),LWa:"JFMAMJJASOND".split(""),AJa:"January February March April May June July August September October November December".split(" "),KWa:"January February March April May June July August September October November December".split(" "),nTa:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
NWa:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),X5a:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),PWa:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),WTa:"Sun Mon Tue Wed Thu Fri Sat".split(" "),OWa:"Sun Mon Tue Wed Thu Fri Sat".split(" "),lKa:"SMTWTFS".split(""),MWa:"SMTWTFS".split(""),oTa:["Q1","Q2","Q3","Q4"],yRa:["1st quarter","2nd quarter","3rd quarter","4th quarter"],Fea:["AM","PM"],Ina:["EEEE, MMMM d, y","MMMM d, y","MMM d, y",
"M/d/yy"],FZa:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],Jna:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],BZ:6,Y5a:[5,6],CZ:5},uhb=thb;uhb=thb;g.k=Qgb.prototype;g.k.xT=uhb.BZ;g.k.zT=uhb.CZ;g.k.clone=function(){var a=new Qgb(this.date);a.xT=this.xT;a.zT=this.zT;return a};
g.k.getFullYear=function(){return this.date.getFullYear()};
g.k.getYear=function(){return this.getFullYear()};
g.k.getMonth=function(){return this.date.getMonth()};
g.k.getDate=function(){return this.date.getDate()};
g.k.getTime=function(){return this.date.getTime()};
g.k.getDay=function(){return this.date.getDay()};
g.k.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.k.getUTCMonth=function(){return this.date.getUTCMonth()};
g.k.getUTCDate=function(){return this.date.getUTCDate()};
g.k.getUTCDay=function(){return this.date.getDay()};
g.k.getUTCHours=function(){return this.date.getUTCHours()};
g.k.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.k.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.k.set=function(a){this.date=new Date(a.getFullYear(),a.getMonth(),a.getDate())};
g.k.setFullYear=function(a){this.date.setFullYear(a)};
g.k.setYear=function(a){this.setFullYear(a)};
g.k.setMonth=function(a){this.date.setMonth(a)};
g.k.setDate=function(a){this.date.setDate(a)};
g.k.setTime=function(a){this.date.setTime(a)};
g.k.setUTCFullYear=function(a){this.date.setUTCFullYear(a)};
g.k.setUTCMonth=function(a){this.date.setUTCMonth(a)};
g.k.setUTCDate=function(a){this.date.setUTCDate(a)};
g.k.add=function(a){if(a.u||a.j){var b=this.getMonth()+a.j+12*a.u,c=this.getYear()+Math.floor(b/12);b%=12;0>b&&(b+=12);a:{switch(b){case 1:var d=0!=c%4||0==c%100&&0!=c%400?28:29;break a;case 5:case 8:case 10:case 3:d=30;break a}d=31}d=Math.min(d,this.getDate());this.setDate(1);this.setFullYear(c);this.setMonth(b);this.setDate(d)}a.days&&(c=this.getYear(),b=0<=c&&99>=c?-1900:0,a=new Date((new Date(c,this.getMonth(),this.getDate(),12)).getTime()+864E5*a.days),this.setDate(1),this.setFullYear(a.getFullYear()+
b),this.setMonth(a.getMonth()),this.setDate(a.getDate()),p6(this,a.getDate()))};
g.k.equals=function(a){return!(!a||this.getYear()!=a.getYear()||this.getMonth()!=a.getMonth()||this.getDate()!=a.getDate())};
g.k.toString=function(){var a=this.getFullYear(),b=0>a?"-":1E4<=a?"+":"";return[b+Mgb(Math.abs(a),b?6:4),Mgb(this.getMonth()+1,2),Mgb(this.getDate(),2)].join("")+""};
g.k.valueOf=function(){return this.date.valueOf()};var vhb=new g.Ar("addUpcomingEventReminderEndpoint");var whb=new g.Ar("removeUpcomingEventReminderEndpoint");var xhb=new g.Ar("updateUpcomingEventReminderButtonStateCommand");var Tgb=new g.Ar("upcomingEventReminderButtonRenderer"),Zgb=new g.Ar("upcomingEventReminderButtonStateRenderer");g.x(q6,g.yS);q6.prototype.hide=function(){this.buttonElement&&this.buttonElement.removeAttribute("aria-haspopup");g.yS.prototype.hide.call(this)};
q6.prototype.show=function(){this.buttonElement&&this.buttonElement.setAttribute("aria-haspopup","true");g.yS.prototype.show.call(this)};
q6.prototype.qa=function(){g.ib(this.j);g.yS.prototype.qa.call(this)};g.x(r6,g.V);
r6.prototype.D=function(){if(this.toggleButtonRenderer){var a=this.toggleButtonRenderer;a.isToggled?this.B(a.toggledServiceEndpoint):this.B(a.defaultServiceEndpoint);a.isToggled=!a.isToggled;s6(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.j&&this.j.zb)this.j.Hb();else{var b=Wgb(this);b&&this.B(b.serviceEndpoint||b.command);b=(null==(a=g.S(null==b?void 0:b.command,g.sQ))?void 0:a.commands)||[];a:{a=g.w(b);for(var c=a.next();!c.done;c=a.next()){var d=b=void 0;if(c=null==(b=g.S(c.value,
g.y$a))?void 0:null==(d=b.popup)?void 0:d.menuPopupRenderer){a=c;break a}}a=void 0}this.j||(this.j=new q6(this.F,this.buttonElement),this.j.Ga(this.element),g.J(this,this.j),this.j.subscribe("reminderMenuItemClicked",this.B,this));b=this.j;b.menuPopupRenderer=a;Sgb(b)}};
r6.prototype.B=function(a){var b=g.S(a,vhb),c=g.S(a,whb);if(a&&(b||c)){if(b){var d=b;var e="notification/add_upcoming_event_reminder"}else c&&(d=c,e="notification/remove_upcoming_event_reminder");if(e&&d&&d.params)for(Ygb(this,e,d.params),a=g.w(d.commands||[]),b=a.next();!b.done;b=a.next())if((b=b.value)&&g.S(b,xhb)){this.u=g.S(b,xhb).state;s6(this);break}}};g.x($gb,g.V);g.k=$gb.prototype;g.k.getPlayerType=function(){if(8===this.api.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.k.Qa=function(a){var b,c,d=null==a?void 0:null==(b=a.liveStreamability)?void 0:null==(c=b.liveStreamabilityRenderer)?void 0:c.offlineSlate;if(d){this.u=a;b=d.liveStreamOfflineSlateRenderer;b.canShowCountdown?this.FY():ahb(this,b);var e,f,h,l;if(c=null==a?void 0:null==(e=a.liveStreamability)?void 0:null==(f=e.liveStreamabilityRenderer)?void 0:null==(h=f.offlineSlate)?void 0:null==(l=h.liveStreamOfflineSlateRenderer)?void 0:l.thumbnail){e=0;f=null;h=c.thumbnails;for(l=0;l<h.length;l++)h[l].width>
e&&(e=h[l].width||0,f=h[l].url);f&&(this.background.style.backgroundImage="url("+f+")")}else this.background.style.backgroundImage="";b.actionButtons||b.reminderButton?(this.j||(this.j=new r6(this.api),this.j.Ga(this.Da("ytp-offline-slate-buttons")),g.J(this,this.j)),Ugb(this.j,b.actionButtons&&b.actionButtons[0],b.reminderButton)):this.j&&Ugb(this.j,null,null);this.u=a}else this.u=null;this.JY()};
g.k.JY=function(a){if(8===this.api.getPresentingPlayerType())var b=!0;else{var c=this.api.Eb(),d=this.getVideoData();b=d.isLivePlayback&&(g.jP(c)||g.hO(c,2)||g.hO(c,64));var e=2===d.autonavState&&g.hO(c,2);c=c.fd()&&!g.WM(d)&&!this.api.isAtLiveHead(void 0,!0);b=b&&!c&&!e}b&&this.u?this.zb?(null==a?0:g.pO(a,2))&&!this.getVideoData().vl&&(g.Sp(this.element,"ytp-offline-slate-collapsed"),this.C.stop(),g.Sp(this.B,"ytp-offline-slate-bar-fade"),this.D.start()):(this.show(),this.C.start(),this.api.ma("offlineslatestatechange"),
this.I&&this.api.Sz()):this.zb&&(this.hide(),this.api.ma("offlineslatestatechange"))};
g.k.FY=function(){var a,b,c,d,e=null==(a=this.u)?void 0:null==(b=a.liveStreamability)?void 0:null==(c=b.liveStreamabilityRenderer)?void 0:null==(d=c.offlineSlate)?void 0:d.liveStreamOfflineSlateRenderer;e&&(a=Math.floor(g.Va()/1E3),b=e.canShowCountdown&&Number(e.scheduledStartTime),!b||b<=a?(ahb(this,e),this.countdownTimer.stop()):(ahb(this,e,g.fR(b-a)),g.Jp(this.countdownTimer)))};
g.k.qa=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.V.prototype.qa.call(this)};t6.prototype.u=function(a){return this.trigger&&a.trigger?this.module===a.module&&this.trigger===a.trigger&&this.j===a.j:!1};
t6.prototype.isExpired=function(){return 6E4<(0,g.QA)()-this.B};
t6.prototype.toString=function(){return this.module+":"+this.trigger+":"+this.j};g.x(ihb,g.sT);g.k=ihb.prototype;g.k.qa=function(){x6(this);this.player.lf("heartbeat");g.sT.prototype.qa.call(this)};
g.k.onCueRangeEnter=function(){this.J=!0;v6(this,2E3)};
g.k.YC=function(a){this.heartbeatParams=a;v6(this,2E3)};
g.k.d_=function(a){var b;8!==this.player.getPresentingPlayerType()&&"UNPLAYABLE"!==(null==(b=this.j)?void 0:b.status)&&(g.hO(a.state,2)||g.hO(a.state,64)?(x6(this),this.C&&(this.J=!0,v6(this,1E3))):(g.hO(a.state,1)||g.hO(a.state,8))&&v6(this,2E3))};
g.k.e_=function(){3!==this.player.getPresentingPlayerType()&&v6(this,2E3)};
g.k.getPlayerType=function(){if(8===this.player.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.k.Xk=function(a){switch(a){case 4:case 3:return!1}return!0};
g.k.zG=function(a,b,c){a={trigger:a,reason:b};c&&(a.serializedServerContext=c.additionalLoggingData);g.xA("heartbeatActionPlayerTransitioned",a)};
g.k.Bf=function(a){var b="LICENSE",c=lhb(a);if(c)return c.reason||g.TT[b]||"";(a=a.match(mhb))&&(a=Number(a[1]))&&(b=g.Pza(a));return g.TT[b]||""};
g.k.wC=function(){return!!this.offlineSlate&&this.offlineSlate.zb};
var mhb=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.rT("heartbeat",ihb);})(_yt_player);
